name: Deploy to GitHub Pages
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.2.0]
    steps:
      - uses: actions/checkout@v3
      - name: install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Deploy to production
        uses: konvasil/deploy-to-github-pages-action@deploy
        env:
          AUTHOR: konvasilakos
          BUILD_PATH: public
          GITHUB_PAGE_NAME: konvasil/ltt.github.io
          PA_TOKEN: ${{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}}
          USERNAME: awibox
          EMAIL: konstantinos.vasilakos@gmail.com
